---
- name: Create Node Exporter systemd service
  ansible.builtin.template:
    src: "node_exporter.service.j2"
    dest: "/etc/systemd/system/{{ node_exporter_service_name }}.service"
    owner: root
    group: root
    mode: '0644'
    backup: true
  become: true
  notify:
    - reload systemd
    - restart node_exporter
  tags:
    - systemd
    - configuration

- name: Configure firewall for Node Exporter (UFW)
  community.general.ufw:
    rule: allow
    port: "{{ node_exporter_port }}"
    proto: tcp
    comment: "{{ node_exporter_firewall_comment }}"
  when: 
    - node_exporter_configure_firewall
    - ansible_os_family == "Debian"
  become: true
  tags:
    - firewall
    - ufw

- name: Configure firewall for Node Exporter (firewalld)
  ansible.posix.firewalld:
    port: "{{ node_exporter_port }}/tcp"
    permanent: true
    state: enabled
    immediate: true
  when:
    - node_exporter_configure_firewall
    - ansible_os_family == "RedHat"
  become: true
  tags:
    - firewall
    - firewalld

- name: Configure firewall for Node Exporter (iptables)
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    destination_port: "{{ node_exporter_port }}"
    jump: ACCEPT
    comment: "{{ node_exporter_firewall_comment }}"
  when:
    - node_exporter_configure_firewall
    - ansible_os_family not in ["Debian", "RedHat"]
  become: true
  tags:
    - firewall
    - iptables
