---
- name: Enable and start node_exporter service
  ansible.builtin.systemd:
    name: "{{ node_exporter_service_name }}"
    enabled: "{{ node_exporter_service_enabled }}"
    state: "{{ node_exporter_service_state }}"
    daemon_reload: true
  become: true
  tags:
    - service
    - node-exporter-start

- name: Ensure node_exporter service is running
  ansible.builtin.systemd:
    name: "{{ node_exporter_service_name }}"
    state: started
  become: true
  tags:
    - service-check
