---
- name: Wait for Node Exporter to be ready
  ansible.builtin.wait_for:
    port: "{{ node_exporter_port }}"
    host: "{{ node_exporter_listen_address }}"
    timeout: "{{ node_exporter_health_check_timeout }}"
  tags:
    - health-check
    - port-check

- name: Check Node Exporter health endpoint
  ansible.builtin.uri:
    url: "http://{{ node_exporter_listen_address }}:{{ node_exporter_port }}/metrics"
    method: GET
    status_code: 200
    timeout: "{{ node_exporter_health_check_timeout }}"
  register: node_exporter_health
  until: node_exporter_health.status == 200
  retries: "{{ node_exporter_health_check_retries }}"
  delay: "{{ node_exporter_health_check_delay }}"
  tags:
    - health-check
    - node-exporter-verify

- name: Get Node Exporter service status
  ansible.builtin.systemd:
    name: "{{ node_exporter_service_name }}"
  register: node_exporter_service_status
  tags:
    - service-status

- name: Display Node Exporter information
  ansible.builtin.debug:
    msg: |
      Node Exporter Status:
      =====================
      Service: {{ node_exporter_service_status.status.ActiveState }}
      Version: {{ node_exporter_version }}
      Listen Address: {{ node_exporter_web_listen_address }}
      Metrics URL: http://{{ ansible_default_ipv4.address }}:{{ node_exporter_port }}/metrics
      
      Service Details:
      - Binary: {{ node_exporter_binary_path }}
      - User: {{ node_exporter_user }}
      - Config Directory: {{ node_exporter_config_dir }}
      
      Health Check: {{ 'PASSED' if node_exporter_health.status == 200 else 'FAILED' }}
  tags:
    - info
    - node-exporter-info
