---
# Clean up any existing Docker installations and repositories
- name: Clean up existing Docker installation
  tags:
    - docker
    - docker-setup
    - docker-cleanup
  block:
    - name: Clean up old Docker apt keys and sources
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - "/etc/apt/trusted.gpg.d/docker.asc"
        - "/etc/apt/sources.list.d/download_docker_com_linux_{{ ansible_distribution_release }}.list"
        - "/etc/apt/sources.list.d/docker.list"
        - "/etc/apt/sources.list.d/docker-ce.list"
        - "/etc/apt/sources.list.d/download_docker_com_linux_ubuntu.list"
        - "/etc/apt/sources.list.d/{{ docker_apt_filename }}.list"
      ignore_errors: yes
      
    - name: Ensure no old Docker repository exists
      apt_repository:
        repo: "deb [arch={{ docker_apt_arch }} signed-by=/etc/apt/trusted.gpg.d/docker.asc] {{ docker_repo_url }}/{{ docker_apt_ansible_distribution | lower }} {{ ansible_distribution_release }} {{ docker_apt_release_channel }}"
        state: absent
        update_cache: false
      ignore_errors: yes
      when: docker_add_repo | bool
      
    - name: Ensure old versions of Docker are not installed
      package:
        name: "{{ docker_obsolete_packages }}"
        state: absent

# Setup new Docker repository
- name: Setup Docker repository
  tags:
    - docker
    - docker-setup
    - docker-repo
  block:
    - name: Ensure APT directories exist
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - "/var/lib/apt/lists/"
        - "/etc/apt/keyrings"

    - name: Install dependencies for Docker repository
      apt:
        name:
          - apt-transport-https
          - ca-certificates
        state: present
        update_cache: yes
        cache_valid_time: 3600

    - name: Add Docker apt key
      get_url:
        url: "{{ docker_apt_gpg_key }}"
        dest: /etc/apt/keyrings/docker.asc
        mode: '0644'
        checksum: "{{ docker_apt_gpg_key_checksum }}"
      register: add_repository_key
      ignore_errors: "{{ docker_apt_ignore_key_error }}"

    - name: Add Docker repository
      copy:
        content: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
        dest: "/etc/apt/sources.list.d/{{ docker_apt_filename | default('docker') }}.list"
        owner: root
        group: root
        mode: '0644'
      register: docker_repo_added

    - name: Update apt cache
      apt:
        update_cache: yes
      when: add_repository_key is not failed and docker_repo_added is changed

# Install Docker packages
- name: Install Docker packages
  apt:
    name: "{{ docker_packages }}"
    state: "{{ docker_packages_state }}"
    update_cache: yes
  when: docker_add_repo | bool
  tags:
    - docker
    - docker-setup
    - docker-install
