---
- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  become: true

- name: restart node_exporter
  ansible.builtin.systemd:
    name: "{{ node_exporter_service_name }}"
    state: restarted
  become: true

- name: stop node_exporter
  ansible.builtin.systemd:
    name: "{{ node_exporter_service_name }}"
    state: stopped
  become: true

- name: start node_exporter
  ansible.builtin.systemd:
    name: "{{ node_exporter_service_name }}"
    state: started
  become: true
