---
- name: Create Gitea container directory
  ansible.builtin.file:
    path: "{{ gitea_container_dir }}"
    state: directory
    mode: '0755'
    owner: "{{ gitea_user }}"
    group: "{{ gitea_group }}"

- name: Create Gitea data directory
  ansible.builtin.file:
    path: "{{ gitea_data_path }}"
    state: directory
    mode: '0755'
    owner: "{{ gitea_user }}"
    group: "{{ gitea_group }}"

- name: Ensure ansible user can access git directories
  ansible.builtin.file:
    path: "{{ gitea_home }}"
    mode: '0755'
    owner: "{{ gitea_user }}"
    group: "{{ gitea_group }}"