---
- name: Configure Docker daemon settings
  ansible.builtin.template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: '0644'
    backup: true
  notify: restart docker
  when: docker_daemon_config is defined
  tags:
    - docker-config

- name: Start and enable Docker service
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: true
  become: true
  tags:
    - docker-service

- name: Configure Docker log rotation
  ansible.builtin.template:
    src: docker-logrotate.j2
    dest: /etc/logrotate.d/docker
    owner: root
    group: root
    mode: '0644'
  when: docker_log_rotation_enabled | default(true)
  tags:
    - docker-logging