---
dependencies: []
galaxy_info:
  role_name: node-exporter
  description: Prometheus Node Exporter installation and configuration
  author: Matt Wisnowski
  company: Wiz-Ops
  company_url: https://wiz-ops.com
  license: MIT
  min_ansible_version: "2.18"
  platforms:
    - name: Ubuntu
      versions:
        - bionic
        - focal
        - jammy
        - noble
