---
# Node Exporter version and download settings
node_exporter_version: "1.7.0"
node_exporter_arch: "linux-amd64"
node_exporter_download_url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.{{ node_exporter_arch }}.tar.gz"

# Node Exporter user and group settings
node_exporter_user: "node_exporter"
node_exporter_user_id: 1010
node_exporter_group_id: 1010
node_exporter_user_home: "/home/{{ node_exporter_user }}"
node_exporter_group_name: "{{ node_exporter_user }}"

# Installation paths
node_exporter_user: "node_exporter"
node_exporter_group: "{{ node_exporter_user }}"
node_exporter_dir: "/opt/node_exporter"
node_exporter_binary_path: "{{ node_exporter_dir }}/node_exporter"
node_exporter_config_dir: "/etc/node_exporter"

# Service configuration
node_exporter_port: 5100
node_exporter_listen_address: "0.0.0.0"
node_exporter_web_listen_address: "{{ node_exporter_listen_address }}:{{ node_exporter_port }}"

# Systemd service settings
node_exporter_service_name: "node_exporter"
node_exporter_service_enabled: true
node_exporter_service_state: "started"

# Firewall configuration
node_exporter_configure_firewall: true
node_exporter_firewall_comment: "Node Exporter metrics"

# Health check settings
node_exporter_health_check_enabled: true
node_exporter_health_check_retries: 5
node_exporter_health_check_delay: 2
node_exporter_health_check_timeout: 10

# Cleanup settings
node_exporter_cleanup_downloads: true

# Node Exporter command line arguments
node_exporter_extra_args: []
# Example:
# node_exporter_extra_args:
#   - '--collector.systemd'
#   - '--collector.processes'
#   - '--no-collector.hwmon'

# Collectors configuration
node_exporter_enabled_collectors: []
node_exporter_disabled_collectors: []

# Web configuration
node_exporter_web_max_requests: 40
node_exporter_web_disable_exporter_metrics: false

# Logging
node_exporter_log_level: "info"
node_exporter_log_format: "logfmt"
