---
dependencies: []
galaxy_info:
  role_name: prometheus
  author: Matt Wisnowski
  company: Wiz-Ops
  company_url: https://wiz-ops.com
  description: Prometheus monitoring server
  license: MIT
  min_ansible_version: "2.18"
  platforms:
    - name: Ubuntu
      versions:
        - bionic
        - focal
        - jammy
        - noble