---
- name: Create Prometheus directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'
  loop:
    - "{{ prometheus_dir }}"
    - "{{ prometheus_data_dir }}"
    - "{{ prometheus_config_dir }}"
  become: true
  tags:
    - directories

- name: Set correct permissions for Prometheus data directory
  ansible.builtin.file:
    path: "{{ prometheus_data_dir }}"
    owner: "{{ prometheus_user_id }}"
    group: "{{ prometheus_group_id }}"
    mode: '0755'
    recurse: true
  become: true
  tags:
    - permissions
