---
- name: Install and Configure Tailscale
  hosts: tailscale
  become: true
  gather_facts: true
  tags:
    - tailscale
    - vpn

  tasks:
    - name: Download Tailscale GPG key
      ansible.builtin.get_url:
        url: https://pkgs.tailscale.com/stable/ubuntu/noble.noarmor.gpg
        dest: /usr/share/keyrings/tailscale-archive-keyring.gpg
        mode: '0644'
      tags:
        - tailscale-repo

    - name: Add Tailscale repository
      ansible.builtin.get_url:
        url: "https://pkgs.tailscale.com/stable/ubuntu/noble.tailscale-keyring.list"
        dest: /etc/apt/sources.list.d/tailscale.list
        mode: '0644'
      tags:
        - tailscale-repo

    - name: Install Tailscale
      ansible.builtin.apt:
        name: tailscale
        state: present
        update_cache: true
      tags:
        - tailscale-install

    - name: Check Tailscale status
      ansible.builtin.command: tailscale status
      register: tailscale_status
      changed_when: false
      failed_when: false
      tags:
        - tailscale-verify

    - name: Display Tailscale status
      ansible.builtin.debug:
        msg: "Tailscale status: {{ tailscale_status.stdout if tailscale_status.rc == 0 else 'Not authenticated - run tailscale up' }}"
      tags:
        - tailscale-verify
