---
- name: Create Grocy directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'
  loop:
    - "{{ grocy_dir }}"
    - "{{ grocy_config_dir }}"
  become: true
  tags:
    - directories

- name: Set correct permissions for Grocy directories
  ansible.builtin.file:
    path: "{{ grocy_dir }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'
    recurse: true
  become: true
  tags:
    - permissions