---
- name: Create 'grocy' group for Grocy
  ansible.builtin.group:
    name: "{{ grocy_group }}"
    gid: "{{ grocy_group_id }}"
    state: present
  become: true

- name: Create 'grocy' user for Grocy
  ansible.builtin.user:
    name: "{{ grocy_user }}"
    uid: "{{ grocy_user_id }}"
    group: "{{ grocy_group }}"
    groups: docker
    append: true
    shell: /bin/bash
    state: present
  become: true